apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahmadsiddiqui-31270-redis-deployment
  labels:
    app: redis
spec:
  replicas: 0
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 3127
