apiVersion: v1
kind: Pod
metadata:
  name: ahmadsiddiqui-31270-redis-pod
  labels:
    app: redis
    role: database
spec:
  containers:
    - name: redis-container
      image: redis:latest
      ports:
        - containerPort: 3127
